--INSERT NON UNIQUE SAMPLE DATA INTO TABLE

--CREATE TABLE DBO.TEST

CREATE TABLE DBO.TEST
(
    ID INT NOT NULL,
    SAMPLE1 CHAR(36) NOT NULL,
    SAMPLE2 CHAR(216) NOT NULL
);

--INSERT SAMPLE DUMMY DATA TO WORK 

Declare @ID  int = 0;
 While @ID < 10000
  Begin
   set @ID = @ID + 1;
   Insert into DBO.TEST (ID,SAMPLE1,SAMPLE2) 
   values (@ID % 100,'a'+ CAST(@ID AS CHAR(36)),'b' + CAST(@ID AS CHAR(216)))
  End;

--CHECK INSERTED DATA INTO TABLE TEST

Select TOP 1000 ID ,SAMPLE1,SAMPLE2 from DBO.TEST