USE TSQL2012NEW

--CREATE A TABLE WITH DUPLICATES IN IT

CREATE TABLE TABLEWITHDUPLICATEDATA(
									DATAFIELD1 varchar(50) NOT NULL,
									DATAFIELD2 varchar(50) NOT NULL,
									DATAFIELD3 char(10) NOT NULL    )
 
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('J', 'D','T')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('M', 'S','W')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('N', 'P','Z')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('L', 'S','A')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('S', 'T','K')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('B', 'A','T')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('J', 'D','T')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('J', 'D','T')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('M', 'S','W')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('N', 'T','F')
INSERT INTO TABLEWITHDUPLICATEDATA(DATAFIELD1, DATAFIELD2, DATAFIELD3) VALUES('J', 'D','T')
 
SELECT * FROM TABLEWITHDUPLICATEDATA

--USE ROW_NUMBER FUNCTION TO SEE IN ALL THREE DATA FIELDS HOW MANY DUPLICATES WE HAVE

SELECT DATAFIELD1, DATAFIELD2, DATAFIELD3
    , ROW_NUMBER() OVER(PARTITION BY DATAFIELD1, DATAFIELD2, DATAFIELD3 ORDER BY DATAFIELD1) AS RNUMBER
FROM TABLEWITHDUPLICATEDATA

--TRY TO REMOVE THOSE DUPLICATE DATA FIELDS WITH CTE

;WITH CTE AS
(
SELECT   DATAFIELD1, DATAFIELD2, DATAFIELD3
        ,ROW_NUMBER() OVER(PARTITION BY DATAFIELD1, DATAFIELD2, DATAFIELD3
         ORDER BY DATAFIELD1) AS RNUMBER
FROM TABLEWITHDUPLICATEDATA
)
DELETE FROM CTE WHERE RNUMBER <> 1

--CHECK 

SELECT * FROM TABLEWITHDUPLICATEDATA

